FROM nvidia/vulkan:1.3-470

ENV RUST_HOME /usr/local/lib/rust
ENV RUSTUP_HOME ${RUST_HOME}/rustup
ENV CARGO_HOME ${RUST_HOME}/cargo
ENV DEBIAN_FRONTEND=noninteractive


RUN apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/3bf863cc.pub \
    && apt-get -y update \
    && apt-get -y upgrade \
    && apt-get install -y --no-install-recommends \
        curl \
        build-essential \
        zlib1g-dev \
        libffi-dev \
        libbz2-dev \
        ca-certificates \
        libsqlite3-dev \
        libssl-dev \
        liblzma-dev \
        libgtk2.0-0 \
        libxkbcommon-x11-0 \
    && apt-get clean


RUN mkdir /usr/local/lib/rust \
    && chmod 0755 $RUST_HOME \
    && curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > ${RUST_HOME}/rustup.sh \
    && chmod +x ${RUST_HOME}/rustup.sh \
    && ${RUST_HOME}/rustup.sh -y --default-toolchain nightly --no-modify-path
ENV PATH $PATH:$CARGO_HOME/bin